### ISSUE TITLE
Possibility to generate font/space values via function

### ISSUE THREAD

**Issue by Zuzuesque** [trys/postcss-utopia#6]
I wondered if there are plans to include font/space variants of the utopia.clamp() function?

Unless you are familiar with the system (or consult the website), there is no easy way to tell whether a space scale with 4 positive steps will generate a --space-3xl property or not. It's not terrible, but it's a mental overhead over copying the values from the website and seeing what tokens are available at one glance.

What I would hope to do is declare variables on the plugin level (similar to min/max width) and then tell the function which step in the scale I want to output. E.g.
```javascript
// postcss.config.js
module.exports = {
  plugins: {
    'postcss-utopia': {
      minWidth: 320,
      maxWidth: 1080,
      minFontSize: 16,
      maxFontSize: 18,
      minTypeScale: 1.2,
      maxTypeScale: 1.25,
    },
  },
}
``` 
```css
// token.css
:root {
  --typography-sm: utopia.typography(-1);
  --typography-md: utopia.typography(0);
  --typography-lg: utopia.typography(1);
  --typography-xl: utopia.typography(2);
  ...
}
``` 
It may be a bit repetitive over having the plugin generate all the tokens, but it is also more declarative/less magic-y and makes it easier to reason about the tokens you have available.
