### ISSUE TITLE
Feature Request: Support for `container` (CQW) Units in `utopia.clamp` Syntax

### ISSUE THREAD

**Issue by shaal** [trys/postcss-utopia#7]
## Description:
Enhance the postcss-utopia plugin to support the use of CQW units in the `utopia.clamp` syntax.

## Problem Explanation:
The postcss-utopia plugin currently supports the following syntax:

```css
--space-s-m: utopia.clamp(16, 24);
```

This gets compiled to:

```css
--space-s-m: clamp(1rem, .9rem + .5vw, 1.5rem);
```

However, there is no support for `container`, which is supported in other usages of Utopia plugin.

## Proposed Solution:
Add support for CQW units in the `utopia.clamp` syntax. The new feature should allow the following syntax:

```css
--space-s-m: utopia.clamp(16, 24, 'container');
```
This should compile to:

```css
--space-s-m: clamp(1rem, .9rem + .5cqw, 1.5rem);
```
By adding an optional third parameter to the `utopia.clamp` function, users can specify the unit to be used for the middle value. If the third parameter is not provided, the default unit should remain as vw.

## Current Behavior:

```css
/* Input */
:root {
  --space-s-m: utopia.clamp(16, 24);
}

/* Output */
:root {
  --space-s-m: clamp(1rem, .9rem + .5vw, 1.5rem);
}
```
## Proposed Behavior:

```css
/* Input */
:root {
  --space-s-m: utopia.clamp(16, 24, 'container');
}

/* Output */
:root {
  --space-s-m: clamp(1rem, .9rem + .5cqw, 1.5rem);
}
```
